<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "key"
 *
 * Auto generated by Extension Builder 2015-12-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Name',
	'description' => 'Name, 
Vendor, 
key',
	'category' => 'plugin',
	'author' => 'G. Wieldraaijer',
	'author_email' => 'grrrben@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);